runtime: python39  # Specify the Python runtime
entrypoint: gunicorn -b :$PORT app:app  # Command to start your app

env: standard  # Use the standard environment
instance_class: F1  # Instance class, F1 is the smallest instance type

automatic_scaling:
  min_idle_instances: 1  # Minimum number of idle instances
  max_idle_instances: 2  # Maximum number of idle instances
  min_pending_latency: 30ms  # Minimum latency before scaling up
  max_pending_latency: 50ms  # Maximum latency before scaling down
  target_cpu_utilization: 0.65  # CPU utilization target

handlers:
- url: /static  # Handler for static files
  static_dir: static/
- url: /.*  # Handler for all other URLs
  script: auto

env_variables:
  FLASK_ENV: 'production'  # Set Flask environment to production
