runtime: python310  # or the version you are using, e.g., python39, python38
entrypoint: gunicorn -b :$PORT main:app  # Adjust if your Flask app is named differently

env_variables:
  FLASK_ENV: 'production'
  FLASK_APP: 'app.py'  # Ensure this matches the entry point of your Flask application

handlers:
- url: /static
  static_dir: static/



automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

libraries:
- name: Flask
  version: "3.0.3"  # This version should match the one in your requirements.txt
- name: gunicorn
  version: "latest"
